# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WaveBeans
description: >- # this means to ignore newlines until "baseurl:"
  WaveBeans is a set of tools to process audio signals using Kotlin/Java/Scala/etc. You can either use it via command line or develop your own program which can be run as a part of you application.
  Generate signals and new instruments. Change existing signals, wave-files or audio streams. Mix different audio streams together. 
  Research and explore audio signals. Make preparation for machine learning algorithms. And many more.
  Everything using one tool in single- or multi-threaded environment, or even distributing computation across multiple nodes (WIP).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wavebeans.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
#remote_theme: just-the-docs # for github pages
theme: "just-the-docs"


# Theme properties: https://pmarsceill.github.io/just-the-docs/docs/configuration/
logo: "/assets/wavebeans-logo-w-name.png"

aux_links:
  "WaveBeans on GitHub":
    - "https://github.com/WaveBeans/wavebeans"

footer_content: "Copyright &copy; 2020 WaveBeans. Distributed under <a href=\"https://github.com/WaveBeans/wavebeans/blob/master/LICENSE\">Apache 2.0 License.</a>"

# color_scheme: "dark"

exclude: 
  - docs-build

ga_tracking: UA-159312268-1
